### ISSUE TITLE
UI Fix

### ISSUE THREAD

**Issue by Abhishek1350** [tarunkatariaonline/youtube-clone#2]
When opening new page from the bottom of previous page the next page is opening from bottom and not from top. 
Here is solution for that : 

import { useEffect } from "react";
import { useLocation } from 'react-router-dom';

const ScrollToTop = () => {
    const { pathname } = useLocation();

    useEffect(() => {
        window.scrollTo(0, 0);
    }, [pathname]);

    return null;
};

export default ScrollToTop;

Make sure to create a new component  **ScrollToTop**  and add this component in you **App.js** just above the Routes component ( Above the Sidebar ).

Your **App.js** file should look like :

 <ChakraProvider theme={theme}>
      <Router>
      <Header/>
      
      <ScrollToTop />
      <Sidebar/>
        <Routes>
          <Route path='/' element={<Home/>} />
          <Route path='/watch' element={<WatchPage/>}/>
          <Route path='/results' element = {<SearchResultPage/>}/>
      
        </Routes>
      </Router>
     
    </ChakraProvider>

### OR 
In your Home, WatchPage and SearchResutPage, add this one like inside **useEffect**  : 
`window.scrollTo(0, 0)`

**Comment by tarunkatariaonline** [comment]
Thanks for reporting this issue and i solved this.
thanks again.
Tarun Kataria 🚀

**Comment by tarunkatariaonline** [comment]
completed

**Comment by tarunkatariaonline** [comment]
completed

**Comment by tarunkatariaonline** [comment]
completed

**Comment by Abhishek1350** [comment]
Welcome!
